### ISSUE TITLE
should packet.data really be length-prefixed?

### ISSUE THREAD

**Issue by michielbdejong** [interledgerjs/ilp-packet#13]
https://github.com/interledger/rfcs/blob/master/asn1/InterledgerPacket.asn#L43 says that the InterledgerPacket's `data` field should be "a length-prefixed header", and that seems to be what  https://github.com/interledgerjs/ilp-packet/blob/master/index.ts#L22 does.

But when I read the ASN.1 without reading that comment, my interpretation is that `PACKET.type` is an [ASN.1 OpenType](http://www.oss.com/asn1/resources/asn1-made-simple/advanced-topics.html) of the PACKET CLASS, and although I couldn't really find a good reference on asn.1, from what I've read, I would expect `PACKET.&Type ({PacketSet}{@type})` to just be replaceable with e.g. `InterledgerProtocolPayment` if typeId is 1?

cc @justmoon 

see also https://github.com/interledgerjs/clp-packet/issues/10

**Comment by justmoon** [comment]
OER does indeed add a length prefix in this situation. I don't have the reference handy, but we generated plenty of examples using OSS Nokalva's ASN.1 implementation and at one point I did look up the relevant section in the X.696 specification and open types in OER are length-prefixed.

**Comment by michielbdejong** [comment]
Thanks! Looked it up, and adding the length prefix is indeed correct for an ASN.1 Open Type. See 
https://www.itu.int/rec/T-REC-X.696-201408-S/en section 30:
<img width="718" alt="screen shot 2017-09-12 at 08 44 07" src="https://user-images.githubusercontent.com/408412/30311637-916933c4-9796-11e7-881d-bbdfd6b83579.png">
