### ISSUE TITLE
destinationAmount and destinationAccount

### ISSUE THREAD

**Issue by sharafian** [interledgerjs/ilp-packet#2]
It might make more sense to change these fields from `amount` and `account` to `destinationAmount` and `destinationAccount`. Amount and account are only used in the Ledger Plugin Interface's transfer objects, which describe local transfers. Across all the other interledgerjs code, (quoting, payments, etc.) we use `destinationAmount` and `destinationAccount`. It might be clearer if we used the same field names here.

@justmoon @emschwartz

**Comment by justmoon** [comment]
Yeah, I was promoting that myself quite a bit.

It's just so tempting to have the ILP packet be "account, amount and data."

The justification would be that the ILP packet always talks about the destination, so destinationAccount, destinationAmount and destinationData would be sorta redundant.

Don't feel strongly either way.

**Comment by emschwartz** [comment]
The packet format should be `account` and `data` but I think the JS interface for this module could accept either those names or the names with the `destination` prefix, if that makes it more consistent with the rest of the JS implementation.

**Comment by emschwartz** [comment]
I think this issue can be closed now @sharafian
