### ISSUE TITLE
IlpReject incompatible with ASN.1 definition

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/ilp-packet#29]
`serializeIlpReject` puts `triggeredBy` before the `message`, while the ASN.1 definition in [interledger/rfcs#361](https://github.com/interledger/rfcs/pull/361/files#diff-c861058271491750f35507f61eaf660aR46) has the message first. Which one is correct?

Also, it would be useful for `IlpPacket` to export a separate interface for IlpReject (rather than just using IlpRejection).

**Comment by justmoon** [comment]
Let's go with the implementation on this one. The order really doesn't matter and the spec is easiest to change.

**Comment by emschwartz** [comment]
Resolved by https://github.com/interledger/rfcs/pull/361/commits/acec3561fcc9cf2f9fd2002aa7157930cddd474a
