### ISSUE TITLE
ILP v1 compatible release

### ISSUE THREAD

**Issue by bushjames** [interledgerjs/ilp-packet#60]
Hi, I cant see any comments on releases that indicate the different levels of compatibility with the various ILP versions? I need a v1 compatible ilp-packet but am not sure which version I should pull. It looks like master is implementing v4. Many thanks.

**Comment by bushjames** [comment]
bump

**Comment by adrianhopebailie** [comment]
v2.2.0 was the last version targeting the legacy packet format.

https://github.com/interledgerjs/ilp-packet/tree/2991d876ca7ccc291e0757ef615ad82dcc961e36

**Comment by bushjames** [comment]
many thanks @adrianhopebailie
